name: Test
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 10.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Nodejs
      uses: actions/setup-node@v1
    - name: Install node_modules
      run: npm install
    - name: Test circom circuits
      run: npm run test
